/** Stable parser text mapped to translated messages; technical values stay untouched. */
export const diagnosticTemplates = {
  diagnostic_000: "The top level of a configuration profile must be a dictionary.",
  diagnostic_001: "Missing required key {p0}.",
  diagnostic_002: "{p0} must be a {p1}, found {p2}.",
  diagnostic_003: 'Top-level PayloadType must be "Configuration", found "{p0}".',
  diagnostic_004: "PayloadIdentifier is empty.",
  diagnostic_005: 'PayloadIdentifier "{p0}" is also used by {p1}.',
  diagnostic_006: "PayloadIdentifier should not contain spaces (reverse-DNS style is expected).",
  diagnostic_007: 'PayloadUUID "{p0}" is not a standard UUID.',
  diagnostic_008: "PayloadUUID duplicates the one in {p0}.",
  diagnostic_009: "PayloadVersion is usually 1, found {p0}.",
  diagnostic_010: "PayloadDisplayName must be a string.",
  diagnostic_011: "No PayloadDisplayName \u2014 the profile will show a generic name in Settings.",
  diagnostic_012: 'PayloadScope must be "System" or "User".',
  diagnostic_013: "PayloadRemovalDisallowed must be a boolean.",
  diagnostic_014: "PayloadExpirationDate must be a date.",
  diagnostic_015: "PayloadExpirationDate is in the past \u2014 the profile is already expired.",
  diagnostic_016: "Missing PayloadContent (the list of payloads).",
  diagnostic_017: "PayloadContent must be an array, found {p0}.",
  diagnostic_018: "PayloadContent is empty \u2014 the profile installs nothing.",
  diagnostic_019: "Each payload must be a dictionary.",
  diagnostic_020: "The top level of an entitlements file must be a dictionary.",
  diagnostic_021: "Duplicate key \u2014 only one value will be used.",
  diagnostic_022: "Must be a boolean, found {p0}.",
  diagnostic_023: "Must be an array of strings, found {p0}.",
  diagnostic_024: "Every item must be a string.",
  diagnostic_025: "Must be a string, found {p0}.",
  diagnostic_026: "Security: {p0}",
  diagnostic_027:
    "get-task-allow is true (debug build). App Store and TestFlight uploads will be rejected.",
  diagnostic_028: 'Must be "development" or "production".',
  diagnostic_029: '"{p0}" needs a service prefix such as applinks: or webcredentials:.',
  diagnostic_030: '"{p0}" must be a bare domain, without http(s)://.',
  diagnostic_031: '"{p0}" should start with "group." (iOS) or your Team ID (macOS).',
  diagnostic_032: '"{p0}" does not start with the Team ID ({p1}).',
  diagnostic_033:
    "Sandbox permission keys are set but com.apple.security.app-sandbox is not true \u2014 they have no effect.",
  diagnostic_034: "The top level of a provisioning profile must be a dictionary.",
  diagnostic_035: 'UUID "{p0}" is not a standard UUID.',
  diagnostic_036: "Expired on {p0} \u2014 builds signed with it will not install.",
  diagnostic_037: "Expires in {p0} days ({p1}).",
  diagnostic_038: "CreationDate is after ExpirationDate.",
  diagnostic_039: "DeveloperCertificates is empty \u2014 no certificate can sign with it.",
  diagnostic_040: "Every DeveloperCertificates item must be data.",
  diagnostic_041: "ProvisionedDevices must be an array.",
  diagnostic_042: "Both ProvisionedDevices and ProvisionsAllDevices are set.",
  diagnostic_043: "Device {p0} is listed twice.",
  diagnostic_044: ".strings files must be a dictionary of strings.",
  diagnostic_045: '"{p0}" is not a string \u2014 .strings only holds strings.',
  diagnostic_046: "A .strings file must be a dictionary.",
  diagnostic_047: "Duplicate key \u2014 the later value silently wins.",
  diagnostic_048: "Value is {p0}; .strings only holds strings.",
  diagnostic_049: "Empty translation.",
  diagnostic_050: "A .stringsdict root must be a dictionary.",
  diagnostic_051: "Each entry must be a dictionary.",
  diagnostic_052: "Missing NSStringLocalizedFormatKey string.",
  diagnostic_053: "NSStringLocalizedFormatKey has no %#@variable@ reference.",
  diagnostic_054: 'Variable "{p0}" is referenced but not defined.',
  diagnostic_055: "Variable definition must be a dictionary.",
  diagnostic_056: "NSStringFormatSpecTypeKey must be NSStringPluralRuleType.",
  diagnostic_057: "Missing NSStringFormatValueTypeKey (e.g. d, ld, lu).",
  diagnostic_058: 'Missing required "other" plural form.',
  diagnostic_059: "Unknown plural category (expected {p0}).",
  diagnostic_060: "Plural form must be a string.",
  diagnostic_061: "Hex must contain an even number of 0-9 / A-F digits",
  diagnostic_062: "config.plist root must be a dictionary",
  diagnostic_063: "Missing required section {p0}",
  diagnostic_064: "{p0} must be a dictionary",
  diagnostic_065: 'Remove sample comment key "{p0}" before booting',
  diagnostic_066: "must be an array",
  diagnostic_067:
    "Drivers entries must be dictionaries (Path/Enabled/LoadEarly/Arguments) since OpenCore 0.7.3",
  diagnostic_068: "entry must be a dictionary",
  diagnostic_069: "missing {p0}",
  diagnostic_070: "{p0} must be {p1}, found {p2}",
  diagnostic_071: '{p0} "{p1}" must be a Darwin version like 20.0.0 or empty',
  diagnostic_072: "Find ({p0} bytes) and Replace ({p1} bytes) must be the same length",
  diagnostic_073: "{p0} must be empty or the same length as {p1}",
  diagnostic_074: 'ACPI table "{p0}" should be a compiled .aml file',
  diagnostic_075: 'Driver "{p0}" should end in .efi',
  diagnostic_076: 'BundlePath "{p0}" should end in .kext',
  diagnostic_077: '"{p0}" is listed twice (also at index {p1})',
  diagnostic_078: "{p0} is a Lilu plugin but Lilu.kext is not in Kernel \u203a Add",
  diagnostic_079: "{p0} must come after Lilu.kext (index {p1}) \u2014 kexts load in list order",
  diagnostic_080: "OpenRuntime.efi is missing \u2014 it is required for almost every setup",
  diagnostic_081: "Key is not a PCI device path like PciRoot(0x0)/Pci(0x2,0x0)",
  diagnostic_082: "SystemProductName (SMBIOS model, e.g. iMac20,1) is required",
  diagnostic_083:
    "SystemSerialNumber is empty or the sample placeholder \u2014 generate one with GenSMBIOS",
  diagnostic_084: "MLB is empty or the sample placeholder",
  diagnostic_085: "SystemUUID must be a UUID (8-4-4-4-12 hex)",
  diagnostic_086: "SystemUUID is empty or all zeros",
  diagnostic_087: "ROM must be data",
  diagnostic_088: "ROM must be 6 bytes (a MAC address), found {p0}",
  diagnostic_089: "ROM is the sample value 112233445566 \u2014 use your NIC's MAC address",
  diagnostic_090: 'Vault must be Optional, Basic or Secure (got "{p0}")',
  diagnostic_091: "DmgLoading = Any allows unsigned DMG images to load \u2014 security risk",
  diagnostic_092: "SecureBootModel is Disabled \u2014 Apple Secure Boot is off",
  diagnostic_093: "ScanPolicy must be an integer",
  diagnostic_094: "AllowNvramReset is on while Vault is Secure",
  diagnostic_095: "must be data (4 bytes, little-endian)",
  diagnostic_096: "must be 4 bytes, found {p0}",
  diagnostic_097:
    "SIP largely disabled (0x{p0}) \u2014 only do this if a kext or patch requires it",
  diagnostic_098:
    "-no_compat_check disables macOS compatibility checks and blocks software updates",
  diagnostic_099: "#include has an empty path",
  diagnostic_100: 'Included file "{p0}" does not end in .xcconfig',
  diagnostic_101:
    "Malformed condition {p0} \u2014 expected [sdk=iphoneos*], [arch=arm64] or [config=Release]",
  diagnostic_102: 'Unknown condition "{p0}" \u2014 Xcode supports sdk, arch and config',
  diagnostic_103: "Unbalanced variable reference in {p0}",
  diagnostic_104: "{p0}{p1} is already set on line {p2}; this later value wins",
  diagnostic_105: '{p0} must be YES or NO (got "{p1}")',
  diagnostic_106: "{p0} must be a version number such as 16.0",
  diagnostic_107: "DEVELOPMENT_TEAM must be a 10-character Team ID",
  diagnostic_108: "PRODUCT_BUNDLE_IDENTIFIER may only contain letters, digits, hyphens and dots",
  diagnostic_109: "Bitcode is deprecated since Xcode 14 and rejected by the App Store",
  diagnostic_110: "Hardened Runtime off \u2014 macOS apps need it for notarization",
  diagnostic_111:
    "Code signing disabled \u2014 the product cannot be installed on devices or distributed",
  diagnostic_112: "Build-phase scripts run unsandboxed and can read or modify anything on disk",
  diagnostic_113: "Release builds with -Onone ship unoptimised code",
  diagnostic_114: "Testability in Release exposes internal symbols and disables some optimisations",
  diagnostic_115: "DEBUG=1 is defined for Release builds",
  diagnostic_116:
    "{p0} looks like a secret stored in plain text \u2014 .xcconfig files are usually committed to source control",
  diagnostic_117: "The file is empty.",
  diagnostic_118: "XML plist parsing is only available in the browser.",
  diagnostic_119: "This file is not valid XML.",
  diagnostic_120: "The plist is empty \u2014 no root value found.",
  diagnostic_121: "truncated",
  diagnostic_122: "length too large",
  diagnostic_123:
    "Security: lets the app load code signed by anyone \u2014 a common code-injection vector.",
  diagnostic_124: "Security: allows unsigned executable memory, weakening the hardened runtime.",
  diagnostic_125: "Security: allows DYLD_* variables, enabling library injection.",
  diagnostic_126: "Security: disables executable page protection entirely.",
  diagnostic_127: "Security: allows JIT-compiled code; only needed by browsers/runtimes.",
  diagnostic_128: "Security: lets the app attach to other processes as a debugger.",
  diagnostic_129:
    'Malformed #include \u2014 use #include "Other.xcconfig" (or #include? for optional)',
  diagnostic_130: "Not a valid setting \u2014 expected KEY = value, a // comment or an #include",
  diagnostic_131: "Not a binary plist (missing bplist header).",
  diagnostic_132: "Binary plist is truncated.",
  diagnostic_133: "Binary plist references a missing object.",
  diagnostic_134: "Unsupported binary plist marker 0x{p0}.",
  diagnostic_135: "Unexpected character (at character {p0})",
  diagnostic_136: "Unexpected end of file (at character {p0})",
  diagnostic_137: "Expected = after key (at character {p0})",
  diagnostic_138: "Missing closing } (at character {p0})",
  diagnostic_139: "Missing closing ) (at character {p0})",
  diagnostic_140: "Not valid Base64",
  diagnostic_141: "Integer must be between 0 and 0xFFFFFFFF",
  diagnostic_142: "AI analysis is not configured.",
  diagnostic_143: "Too many requests right now \u2014 please try again in a minute.",
  diagnostic_144: "The configured AI provider requires payment or additional credits.",
  diagnostic_145: "AI analysis failed ({p0}).",
} as const;
