import type { Locale } from "@/lib/locales";
import type { LocalizedPage } from "./localized/types";

export const trustPages: Record<Locale, Record<"/about" | "/privacy", LocalizedPage>> = {
  en: {
    "/about": {
      title: "About OpenPlist — Browser-based Apple File Tools",
      description:
        "Learn what OpenPlist does, how its browser-based plist tools work, and the limits of format conversion and configuration diagnostics.",
      h1: "About OpenPlist",
      tagline:
        "Tools for reading, editing and understanding Apple configuration files in a browser.",
      bullets: [],
      sections: [
        {
          heading: "Why this project exists",
          body: "OpenPlist brings a structured property-list editor to Windows, macOS and Linux without requiring Xcode. The project combines typed tree editing, XML and binary conversion, JSON export and specialized views for Apple configuration files. You can start with a synthetic sample before opening your own file.",
        },
        {
          heading: "What the checks mean",
          body: "The parser checks supported file syntax; specialized tools also check selected configuration rules. These checks do not replace Xcode, Apple signing tools, device-management validation or OpenCore's own validation. Viewing a signed profile does not verify its cryptographic signature, and exporting a modified profile does not sign it.",
        },
        {
          heading: "Data and compatibility",
          body: "Core parsing, editing and export run locally in the browser. The editor keeps plist value types internally, but output formats have different capabilities. JSON loses date, data and UID types; export rewrites formatting and removes comments. Numbers use JavaScript precision. Keep originals and verify exported files in the application that uses them.",
        },
      ],
      faq: [
        {
          q: "Is OpenPlist an Apple product?",
          a: "No. OpenPlist is an independent project and is not affiliated with or endorsed by Apple.",
        },
        {
          q: "Can I try it without my own files?",
          a: "Yes. Tool pages provide synthetic examples and the core guides include downloadable XML, binary and JSON samples.",
        },
      ],
    },
    "/privacy": {
      title: "Privacy & Data Handling — OpenPlist",
      description:
        "How OpenPlist handles local files, in-memory editor sessions and optional AI profile review. Understand what stays in the browser and what is sent when you request AI.",
      h1: "Privacy & data handling",
      tagline: "Understand where your file contents are processed before choosing a tool.",
      bullets: [],
      sections: [
        {
          heading: "Opening, editing and converting files",
          body: "The core tools read files using your browser and parse, edit and export them locally. These actions do not send file contents to an OpenPlist server. Choosing a file does not grant access to the rest of your folders. Downloads are generated by the browser.",
        },
        {
          heading: "Editor sessions",
          body: "Open documents and undo history are kept in page memory, including when you switch languages or move between tools in the same session. The app does not save file contents to localStorage or IndexedDB. Reloading or closing the page clears this in-memory session; download your work before leaving.",
        },
        {
          heading: "Optional AI profile review",
          body: "AI review is a separate action available for configuration profiles. Opening the AI panel does not submit the profile. When you select Analyze with AI, the browser redacts selected sensitive fields and sends the remaining profile text to the application server, which forwards it to the configured AI provider. Redaction is rule-based and may miss sensitive information in arbitrary fields; use only content you are comfortable sending. Provider logging and retention policies depend on the service configured by the operator.",
        },
        {
          heading: "Website requests and errors",
          body: "Loading the website still sends ordinary web requests to its hosting infrastructure. Hosting providers may process request metadata such as IP addresses and user agents. Local file processing is not a claim that the browser makes no network requests.",
        },
        {
          heading: "Review before sharing",
          body: "If you report a problem, use a small synthetic example. Remove certificates, private keys, passwords, tokens, personal identifiers and private device or organization details. Do not submit a real profile merely to demonstrate a formatting issue.",
        },
      ],
      faq: [
        {
          q: "Can I use the editor without AI?",
          a: "Yes. Opening, editing, validation and format conversion do not require AI review.",
        },
        {
          q: "Does no upload mean no network traffic?",
          a: "No. The site must load its code and assets, and optional AI review sends profile content only after you request it. Core file operations remain local.",
        },
      ],
    },
  },
  zh: {
    "/about": {
      title: "关于 OpenPlist — 浏览器中的 Apple 文件工具",
      description:
        "了解 OpenPlist 的用途、本地文件处理方式，以及格式转换与配置诊断的能力边界。无需 Xcode，在浏览器中查看和编辑 Apple 配置文件。",
      h1: "关于 OpenPlist",
      tagline: "在浏览器中查看、编辑和理解 Apple 配置文件。",
      bullets: [],
      sections: [
        {
          heading: "为什么做这个项目",
          body: "OpenPlist 希望让 Windows、macOS 和 Linux 用户无需安装 Xcode，也能使用结构化的属性列表编辑器。项目提供带类型的树形编辑、XML 与二进制转换、JSON 导出，以及针对 Apple 配置文件的专用检查。你可以先用合成示例体验，再打开自己的文件。",
        },
        {
          heading: "检查结果代表什么",
          body: "解析器检查支持格式的语法，专用工具还会检查部分配置规则。这些检查不能替代 Xcode、Apple 签名工具、设备管理系统或 OpenCore 自身的验证。查看已签名描述文件不代表验证了其密码学签名，导出修改后的描述文件也不会为其签名。",
        },
        {
          heading: "数据与兼容性",
          body: "核心解析、编辑和导出均在浏览器本地进行。内部模型保留 plist 值类型，但不同输出格式有不同能力：JSON 会丢失 date、data 和 UID 类型；导出会重写格式并删除注释。数字使用 JavaScript 精度。请保留原件，并在使用该文件的目标应用中验证导出结果。",
        },
      ],
      faq: [
        {
          q: "OpenPlist 是 Apple 的产品吗？",
          a: "不是。OpenPlist 是独立项目，与 Apple 没有隶属或背书关系。",
        },
        {
          q: "没有文件也能试用吗？",
          a: "可以。工具页提供合成示例，核心指南还提供可下载的 XML、二进制和 JSON 样例。",
        },
      ],
    },
    "/privacy": {
      title: "隐私与数据处理 — OpenPlist",
      description:
        "了解 OpenPlist 如何处理本地文件、内存中的编辑会话和可选 AI 审查，以及哪些操作会发送内容到服务器。",
      h1: "隐私与数据处理",
      tagline: "选择工具前，先了解文件内容在哪里处理。",
      bullets: [],
      sections: [
        {
          heading: "打开、编辑和转换文件",
          body: "核心工具通过浏览器读取你选择的文件，并在本地解析、编辑和导出。这些操作不会把文件内容发送到 OpenPlist 服务器。选择一个文件不代表允许访问其他文件夹，下载文件也由浏览器生成。",
        },
        {
          heading: "编辑会话",
          body: "打开的文档和撤销历史保存在页面内存中；同一会话内切换语言或工具时会保留。应用不会将文件内容保存到 localStorage 或 IndexedDB。刷新或关闭页面会清除此内存会话，请离开前下载需要保留的修改。",
        },
        {
          heading: "可选的 AI 配置审查",
          body: "AI 审查是配置描述文件工具中的独立操作。仅展开 AI 面板不会提交内容。点击 AI 分析后，浏览器会按规则脱敏部分敏感字段，再将其余文本发送到应用服务器，由服务器转发给配置的 AI 服务商。自动脱敏可能遗漏任意字段中的敏感信息，请仅提交你愿意发送的内容。提供商的日志与数据保留政策取决于运营者配置的服务。",
        },
        {
          heading: "网页请求与错误诊断",
          body: "加载网站仍会向托管基础设施发送普通网页请求。托管服务可能处理 IP 地址、浏览器标识等请求信息。本地文件处理不意味着浏览器完全没有网络请求。",
        },
        {
          heading: "反馈前检查内容",
          body: "报告问题时请使用最小的合成示例，去除证书、私钥、密码、令牌、个人标识以及设备或组织的私有信息。仅为演示格式问题时，不要提交真实描述文件。",
        },
      ],
      faq: [
        {
          q: "不用 AI 也能使用编辑器吗？",
          a: "可以。打开、编辑、校验和格式转换均不需要 AI 审查。",
        },
        {
          q: "无需上传等于没有网络请求吗？",
          a: "不是。网站需要加载代码和资源，可选 AI 审查也会在你主动请求后发送内容；核心文件操作仍在本地完成。",
        },
      ],
    },
  },
  ja: {
    "/about": {
      title: "OpenPlist について — ブラウザーで使う Apple ファイルツール",
      description:
        "OpenPlist の目的、ローカルでのファイル処理、形式変換と設定診断の対応範囲を紹介します。Xcode なしで Apple の設定ファイルを確認・編集できます。",
      h1: "OpenPlist について",
      tagline: "Apple の設定ファイルをブラウザーで確認・編集・理解するためのツールです。",
      bullets: [],
      sections: [
        {
          heading: "このプロジェクトの目的",
          body: "OpenPlist は、Windows・macOS・Linux で Xcode をインストールせずに使える、構造化されたプロパティリスト編集ツールです。型を持つツリーの編集、XML とバイナリの変換、JSON の出力、Apple 設定ファイル専用の検査を提供します。自分のファイルを開く前に、合成サンプルで試せます。",
        },
        {
          heading: "検査結果の意味",
          body: "パーサーは対応形式の構文を確認し、専用ツールは一部の設定ルールも検査します。Xcode、Apple の署名ツール、デバイス管理システム、OpenCore 自身の検証を置き換えるものではありません。署名付きプロファイルの表示は暗号学的な署名検証ではなく、編集したファイルの書き出しでも署名は付けません。",
        },
        {
          heading: "データと互換性",
          body: "基本的な解析・編集・書き出しはブラウザー内で行います。内部では plist の型を保持しますが、出力形式によって表現できる内容は異なります。JSON では date・data・UID 型が失われ、書き出しでは書式を再生成してコメントを削除します。数値は JavaScript の精度を使用します。元のファイルを保管し、利用先のアプリで結果を確認してください。",
        },
      ],
      faq: [
        {
          q: "Apple の製品ですか？",
          a: "いいえ。OpenPlist は独立したプロジェクトで、Apple との提携や Apple による推奨を意味しません。",
        },
        {
          q: "自分のファイルなしで試せますか？",
          a: "はい。ツールには合成サンプルがあり、主要ガイドには XML・バイナリ・JSON のダウンロード可能なサンプルがあります。",
        },
      ],
    },
    "/privacy": {
      title: "プライバシーとデータの扱い — OpenPlist",
      description:
        "ローカルファイル、メモリ内の編集セッション、任意の AI レビューのデータ処理を説明します。どの操作で内容が送信されるかを確認できます。",
      h1: "プライバシーとデータの扱い",
      tagline: "ファイルの内容がどこで処理されるかを確認してからツールを選べます。",
      bullets: [],
      sections: [
        {
          heading: "ファイルの読み込み・編集・変換",
          body: "基本ツールは選択したファイルをブラウザーで読み取り、ローカルで解析・編集・書き出しします。これらの操作で内容を OpenPlist サーバーへ送信することはありません。ファイルの選択は他のフォルダーへのアクセスを許可するものではなく、ダウンロードもブラウザーで生成します。",
        },
        {
          heading: "編集セッション",
          body: "開いた文書と取り消し履歴はページのメモリに保持し、同じセッション内の言語やツールの切り替えでも残ります。ファイルの内容を localStorage や IndexedDB に保存しません。ページを再読み込みするか閉じるとメモリの内容は失われるため、必要な編集結果を先にダウンロードしてください。",
        },
        {
          heading: "任意の AI プロファイルレビュー",
          body: "AI レビューは構成プロファイル向けの独立した操作です。パネルを開くだけでは送信しません。AI 分析を選ぶと、ブラウザーが一部の機密フィールドをルールに従って伏せ、残りをアプリのサーバーへ送信します。サーバーは設定された AI プロバイダーへ転送します。自動処理では任意のフィールドにある機密情報を見落とす場合があるため、送信してよい内容だけを使用してください。ログやデータ保持の方針は、運営者が設定したサービスによって異なります。",
        },
        {
          heading: "ウェブリクエストとエラー診断",
          body: "サイトの読み込み時にはホスティング基盤への通常のリクエストが発生します。ホスティング提供者は IP アドレスやブラウザー情報などを処理する場合があります。ローカル処理は、ネットワーク通信が一切ないという意味ではありません。",
        },
        {
          heading: "問題を報告する前に",
          body: "小さな合成サンプルを使用し、証明書・秘密鍵・パスワード・トークン・個人識別情報・非公開のデバイスや組織情報を除去してください。書式の問題を示すためだけに、実際のプロファイルを送信しないでください。",
        },
      ],
      faq: [
        {
          q: "AI なしで使えますか？",
          a: "はい。読み込み・編集・検査・形式変換に AI レビューは必要ありません。",
        },
        {
          q: "アップロード不要なら通信もありませんか？",
          a: "いいえ。コードとリソースの読み込みが必要で、任意の AI レビューも明示的な依頼後に内容を送信します。基本的なファイル操作はローカルで完結します。",
        },
      ],
    },
  },
};
