/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BinaryPlistEditorRouteImport } from './routes/binary-plist-editor'
import { Route as BinaryPlistToXmlRouteImport } from './routes/binary-plist-to-xml'
import { Route as BinaryPlistViewerRouteImport } from './routes/binary-plist-viewer'
import { Route as EntitlementsEditorRouteImport } from './routes/entitlements-editor'
import { Route as HowToOpenPlistOnWindowsRouteImport } from './routes/how-to-open-plist-on-windows'
import { Route as JsonToPlistRouteImport } from './routes/json-to-plist'
import { Route as MobileconfigEditorRouteImport } from './routes/mobileconfig-editor'
import { Route as MobileprovisionViewerRouteImport } from './routes/mobileprovision-viewer'
import { Route as OpencoreConfigEditorRouteImport } from './routes/opencore-config-editor'
import { Route as PlistEditorRouteImport } from './routes/plist-editor'
import { Route as PlistToJsonRouteImport } from './routes/plist-to-json'
import { Route as PlistToXmlRouteImport } from './routes/plist-to-xml'
import { Route as PlistViewerRouteImport } from './routes/plist-viewer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StringsEditorRouteImport } from './routes/strings-editor'
import { Route as StringsdictEditorRouteImport } from './routes/stringsdict-editor'
import { Route as WhatIsAPlistFileRouteImport } from './routes/what-is-a-plist-file'
import { Route as XcconfigEditorRouteImport } from './routes/xcconfig-editor'
import { Route as XmlToPlistRouteImport } from './routes/xml-to-plist'
import { Route as XmlVsBinaryPlistRouteImport } from './routes/xml-vs-binary-plist'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleBinaryPlistEditorRouteImport } from './routes/$locale/binary-plist-editor'
import { Route as LocaleBinaryPlistToXmlRouteImport } from './routes/$locale/binary-plist-to-xml'
import { Route as LocaleBinaryPlistViewerRouteImport } from './routes/$locale/binary-plist-viewer'
import { Route as LocaleEntitlementsEditorRouteImport } from './routes/$locale/entitlements-editor'
import { Route as LocaleHowToOpenPlistOnWindowsRouteImport } from './routes/$locale/how-to-open-plist-on-windows'
import { Route as LocaleJsonToPlistRouteImport } from './routes/$locale/json-to-plist'
import { Route as LocaleMobileconfigEditorRouteImport } from './routes/$locale/mobileconfig-editor'
import { Route as LocaleMobileprovisionViewerRouteImport } from './routes/$locale/mobileprovision-viewer'
import { Route as LocaleOpencoreConfigEditorRouteImport } from './routes/$locale/opencore-config-editor'
import { Route as LocalePlistEditorRouteImport } from './routes/$locale/plist-editor'
import { Route as LocalePlistToJsonRouteImport } from './routes/$locale/plist-to-json'
import { Route as LocalePlistToXmlRouteImport } from './routes/$locale/plist-to-xml'
import { Route as LocalePlistViewerRouteImport } from './routes/$locale/plist-viewer'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleStringsEditorRouteImport } from './routes/$locale/strings-editor'
import { Route as LocaleStringsdictEditorRouteImport } from './routes/$locale/stringsdict-editor'
import { Route as LocaleWhatIsAPlistFileRouteImport } from './routes/$locale/what-is-a-plist-file'
import { Route as LocaleXcconfigEditorRouteImport } from './routes/$locale/xcconfig-editor'
import { Route as LocaleXmlToPlistRouteImport } from './routes/$locale/xml-to-plist'
import { Route as LocaleXmlVsBinaryPlistRouteImport } from './routes/$locale/xml-vs-binary-plist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BinaryPlistEditorRoute = BinaryPlistEditorRouteImport.update({
  id: '/binary-plist-editor',
  path: '/binary-plist-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const BinaryPlistToXmlRoute = BinaryPlistToXmlRouteImport.update({
  id: '/binary-plist-to-xml',
  path: '/binary-plist-to-xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BinaryPlistViewerRoute = BinaryPlistViewerRouteImport.update({
  id: '/binary-plist-viewer',
  path: '/binary-plist-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitlementsEditorRoute = EntitlementsEditorRouteImport.update({
  id: '/entitlements-editor',
  path: '/entitlements-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOpenPlistOnWindowsRoute = HowToOpenPlistOnWindowsRouteImport.update({
  id: '/how-to-open-plist-on-windows',
  path: '/how-to-open-plist-on-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToPlistRoute = JsonToPlistRouteImport.update({
  id: '/json-to-plist',
  path: '/json-to-plist',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileconfigEditorRoute = MobileconfigEditorRouteImport.update({
  id: '/mobileconfig-editor',
  path: '/mobileconfig-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileprovisionViewerRoute = MobileprovisionViewerRouteImport.update({
  id: '/mobileprovision-viewer',
  path: '/mobileprovision-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencoreConfigEditorRoute = OpencoreConfigEditorRouteImport.update({
  id: '/opencore-config-editor',
  path: '/opencore-config-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlistEditorRoute = PlistEditorRouteImport.update({
  id: '/plist-editor',
  path: '/plist-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlistToJsonRoute = PlistToJsonRouteImport.update({
  id: '/plist-to-json',
  path: '/plist-to-json',
  getParentRoute: () => rootRouteImport,
} as any)
const PlistToXmlRoute = PlistToXmlRouteImport.update({
  id: '/plist-to-xml',
  path: '/plist-to-xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlistViewerRoute = PlistViewerRouteImport.update({
  id: '/plist-viewer',
  path: '/plist-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsEditorRoute = StringsEditorRouteImport.update({
  id: '/strings-editor',
  path: '/strings-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsdictEditorRoute = StringsdictEditorRouteImport.update({
  id: '/stringsdict-editor',
  path: '/stringsdict-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsAPlistFileRoute = WhatIsAPlistFileRouteImport.update({
  id: '/what-is-a-plist-file',
  path: '/what-is-a-plist-file',
  getParentRoute: () => rootRouteImport,
} as any)
const XcconfigEditorRoute = XcconfigEditorRouteImport.update({
  id: '/xcconfig-editor',
  path: '/xcconfig-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlToPlistRoute = XmlToPlistRouteImport.update({
  id: '/xml-to-plist',
  path: '/xml-to-plist',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlVsBinaryPlistRoute = XmlVsBinaryPlistRouteImport.update({
  id: '/xml-vs-binary-plist',
  path: '/xml-vs-binary-plist',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBinaryPlistEditorRoute = LocaleBinaryPlistEditorRouteImport.update({
  id: '/binary-plist-editor',
  path: '/binary-plist-editor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBinaryPlistToXmlRoute = LocaleBinaryPlistToXmlRouteImport.update({
  id: '/binary-plist-to-xml',
  path: '/binary-plist-to-xml',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBinaryPlistViewerRoute = LocaleBinaryPlistViewerRouteImport.update({
  id: '/binary-plist-viewer',
  path: '/binary-plist-viewer',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEntitlementsEditorRoute =
  LocaleEntitlementsEditorRouteImport.update({
    id: '/entitlements-editor',
    path: '/entitlements-editor',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleHowToOpenPlistOnWindowsRoute =
  LocaleHowToOpenPlistOnWindowsRouteImport.update({
    id: '/how-to-open-plist-on-windows',
    path: '/how-to-open-plist-on-windows',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleJsonToPlistRoute = LocaleJsonToPlistRouteImport.update({
  id: '/json-to-plist',
  path: '/json-to-plist',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMobileconfigEditorRoute =
  LocaleMobileconfigEditorRouteImport.update({
    id: '/mobileconfig-editor',
    path: '/mobileconfig-editor',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleMobileprovisionViewerRoute =
  LocaleMobileprovisionViewerRouteImport.update({
    id: '/mobileprovision-viewer',
    path: '/mobileprovision-viewer',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleOpencoreConfigEditorRoute =
  LocaleOpencoreConfigEditorRouteImport.update({
    id: '/opencore-config-editor',
    path: '/opencore-config-editor',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocalePlistEditorRoute = LocalePlistEditorRouteImport.update({
  id: '/plist-editor',
  path: '/plist-editor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlistToJsonRoute = LocalePlistToJsonRouteImport.update({
  id: '/plist-to-json',
  path: '/plist-to-json',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlistToXmlRoute = LocalePlistToXmlRouteImport.update({
  id: '/plist-to-xml',
  path: '/plist-to-xml',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlistViewerRoute = LocalePlistViewerRouteImport.update({
  id: '/plist-viewer',
  path: '/plist-viewer',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleStringsEditorRoute = LocaleStringsEditorRouteImport.update({
  id: '/strings-editor',
  path: '/strings-editor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleStringsdictEditorRoute = LocaleStringsdictEditorRouteImport.update({
  id: '/stringsdict-editor',
  path: '/stringsdict-editor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWhatIsAPlistFileRoute = LocaleWhatIsAPlistFileRouteImport.update({
  id: '/what-is-a-plist-file',
  path: '/what-is-a-plist-file',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleXcconfigEditorRoute = LocaleXcconfigEditorRouteImport.update({
  id: '/xcconfig-editor',
  path: '/xcconfig-editor',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleXmlToPlistRoute = LocaleXmlToPlistRouteImport.update({
  id: '/xml-to-plist',
  path: '/xml-to-plist',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleXmlVsBinaryPlistRoute = LocaleXmlVsBinaryPlistRouteImport.update({
  id: '/xml-vs-binary-plist',
  path: '/xml-vs-binary-plist',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/binary-plist-editor': typeof BinaryPlistEditorRoute
  '/binary-plist-to-xml': typeof BinaryPlistToXmlRoute
  '/binary-plist-viewer': typeof BinaryPlistViewerRoute
  '/entitlements-editor': typeof EntitlementsEditorRoute
  '/how-to-open-plist-on-windows': typeof HowToOpenPlistOnWindowsRoute
  '/json-to-plist': typeof JsonToPlistRoute
  '/mobileconfig-editor': typeof MobileconfigEditorRoute
  '/mobileprovision-viewer': typeof MobileprovisionViewerRoute
  '/opencore-config-editor': typeof OpencoreConfigEditorRoute
  '/plist-editor': typeof PlistEditorRoute
  '/plist-to-json': typeof PlistToJsonRoute
  '/plist-to-xml': typeof PlistToXmlRoute
  '/plist-viewer': typeof PlistViewerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strings-editor': typeof StringsEditorRoute
  '/stringsdict-editor': typeof StringsdictEditorRoute
  '/what-is-a-plist-file': typeof WhatIsAPlistFileRoute
  '/xcconfig-editor': typeof XcconfigEditorRoute
  '/xml-to-plist': typeof XmlToPlistRoute
  '/xml-vs-binary-plist': typeof XmlVsBinaryPlistRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/binary-plist-editor': typeof LocaleBinaryPlistEditorRoute
  '/$locale/binary-plist-to-xml': typeof LocaleBinaryPlistToXmlRoute
  '/$locale/binary-plist-viewer': typeof LocaleBinaryPlistViewerRoute
  '/$locale/entitlements-editor': typeof LocaleEntitlementsEditorRoute
  '/$locale/how-to-open-plist-on-windows': typeof LocaleHowToOpenPlistOnWindowsRoute
  '/$locale/json-to-plist': typeof LocaleJsonToPlistRoute
  '/$locale/mobileconfig-editor': typeof LocaleMobileconfigEditorRoute
  '/$locale/mobileprovision-viewer': typeof LocaleMobileprovisionViewerRoute
  '/$locale/opencore-config-editor': typeof LocaleOpencoreConfigEditorRoute
  '/$locale/plist-editor': typeof LocalePlistEditorRoute
  '/$locale/plist-to-json': typeof LocalePlistToJsonRoute
  '/$locale/plist-to-xml': typeof LocalePlistToXmlRoute
  '/$locale/plist-viewer': typeof LocalePlistViewerRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/strings-editor': typeof LocaleStringsEditorRoute
  '/$locale/stringsdict-editor': typeof LocaleStringsdictEditorRoute
  '/$locale/what-is-a-plist-file': typeof LocaleWhatIsAPlistFileRoute
  '/$locale/xcconfig-editor': typeof LocaleXcconfigEditorRoute
  '/$locale/xml-to-plist': typeof LocaleXmlToPlistRoute
  '/$locale/xml-vs-binary-plist': typeof LocaleXmlVsBinaryPlistRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/binary-plist-editor': typeof BinaryPlistEditorRoute
  '/binary-plist-to-xml': typeof BinaryPlistToXmlRoute
  '/binary-plist-viewer': typeof BinaryPlistViewerRoute
  '/entitlements-editor': typeof EntitlementsEditorRoute
  '/how-to-open-plist-on-windows': typeof HowToOpenPlistOnWindowsRoute
  '/json-to-plist': typeof JsonToPlistRoute
  '/mobileconfig-editor': typeof MobileconfigEditorRoute
  '/mobileprovision-viewer': typeof MobileprovisionViewerRoute
  '/opencore-config-editor': typeof OpencoreConfigEditorRoute
  '/plist-editor': typeof PlistEditorRoute
  '/plist-to-json': typeof PlistToJsonRoute
  '/plist-to-xml': typeof PlistToXmlRoute
  '/plist-viewer': typeof PlistViewerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strings-editor': typeof StringsEditorRoute
  '/stringsdict-editor': typeof StringsdictEditorRoute
  '/what-is-a-plist-file': typeof WhatIsAPlistFileRoute
  '/xcconfig-editor': typeof XcconfigEditorRoute
  '/xml-to-plist': typeof XmlToPlistRoute
  '/xml-vs-binary-plist': typeof XmlVsBinaryPlistRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/binary-plist-editor': typeof LocaleBinaryPlistEditorRoute
  '/$locale/binary-plist-to-xml': typeof LocaleBinaryPlistToXmlRoute
  '/$locale/binary-plist-viewer': typeof LocaleBinaryPlistViewerRoute
  '/$locale/entitlements-editor': typeof LocaleEntitlementsEditorRoute
  '/$locale/how-to-open-plist-on-windows': typeof LocaleHowToOpenPlistOnWindowsRoute
  '/$locale/json-to-plist': typeof LocaleJsonToPlistRoute
  '/$locale/mobileconfig-editor': typeof LocaleMobileconfigEditorRoute
  '/$locale/mobileprovision-viewer': typeof LocaleMobileprovisionViewerRoute
  '/$locale/opencore-config-editor': typeof LocaleOpencoreConfigEditorRoute
  '/$locale/plist-editor': typeof LocalePlistEditorRoute
  '/$locale/plist-to-json': typeof LocalePlistToJsonRoute
  '/$locale/plist-to-xml': typeof LocalePlistToXmlRoute
  '/$locale/plist-viewer': typeof LocalePlistViewerRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/strings-editor': typeof LocaleStringsEditorRoute
  '/$locale/stringsdict-editor': typeof LocaleStringsdictEditorRoute
  '/$locale/what-is-a-plist-file': typeof LocaleWhatIsAPlistFileRoute
  '/$locale/xcconfig-editor': typeof LocaleXcconfigEditorRoute
  '/$locale/xml-to-plist': typeof LocaleXmlToPlistRoute
  '/$locale/xml-vs-binary-plist': typeof LocaleXmlVsBinaryPlistRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/binary-plist-editor': typeof BinaryPlistEditorRoute
  '/binary-plist-to-xml': typeof BinaryPlistToXmlRoute
  '/binary-plist-viewer': typeof BinaryPlistViewerRoute
  '/entitlements-editor': typeof EntitlementsEditorRoute
  '/how-to-open-plist-on-windows': typeof HowToOpenPlistOnWindowsRoute
  '/json-to-plist': typeof JsonToPlistRoute
  '/mobileconfig-editor': typeof MobileconfigEditorRoute
  '/mobileprovision-viewer': typeof MobileprovisionViewerRoute
  '/opencore-config-editor': typeof OpencoreConfigEditorRoute
  '/plist-editor': typeof PlistEditorRoute
  '/plist-to-json': typeof PlistToJsonRoute
  '/plist-to-xml': typeof PlistToXmlRoute
  '/plist-viewer': typeof PlistViewerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strings-editor': typeof StringsEditorRoute
  '/stringsdict-editor': typeof StringsdictEditorRoute
  '/what-is-a-plist-file': typeof WhatIsAPlistFileRoute
  '/xcconfig-editor': typeof XcconfigEditorRoute
  '/xml-to-plist': typeof XmlToPlistRoute
  '/xml-vs-binary-plist': typeof XmlVsBinaryPlistRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/binary-plist-editor': typeof LocaleBinaryPlistEditorRoute
  '/$locale/binary-plist-to-xml': typeof LocaleBinaryPlistToXmlRoute
  '/$locale/binary-plist-viewer': typeof LocaleBinaryPlistViewerRoute
  '/$locale/entitlements-editor': typeof LocaleEntitlementsEditorRoute
  '/$locale/how-to-open-plist-on-windows': typeof LocaleHowToOpenPlistOnWindowsRoute
  '/$locale/json-to-plist': typeof LocaleJsonToPlistRoute
  '/$locale/mobileconfig-editor': typeof LocaleMobileconfigEditorRoute
  '/$locale/mobileprovision-viewer': typeof LocaleMobileprovisionViewerRoute
  '/$locale/opencore-config-editor': typeof LocaleOpencoreConfigEditorRoute
  '/$locale/plist-editor': typeof LocalePlistEditorRoute
  '/$locale/plist-to-json': typeof LocalePlistToJsonRoute
  '/$locale/plist-to-xml': typeof LocalePlistToXmlRoute
  '/$locale/plist-viewer': typeof LocalePlistViewerRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/strings-editor': typeof LocaleStringsEditorRoute
  '/$locale/stringsdict-editor': typeof LocaleStringsdictEditorRoute
  '/$locale/what-is-a-plist-file': typeof LocaleWhatIsAPlistFileRoute
  '/$locale/xcconfig-editor': typeof LocaleXcconfigEditorRoute
  '/$locale/xml-to-plist': typeof LocaleXmlToPlistRoute
  '/$locale/xml-vs-binary-plist': typeof LocaleXmlVsBinaryPlistRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/binary-plist-editor'
    | '/binary-plist-to-xml'
    | '/binary-plist-viewer'
    | '/entitlements-editor'
    | '/how-to-open-plist-on-windows'
    | '/json-to-plist'
    | '/mobileconfig-editor'
    | '/mobileprovision-viewer'
    | '/opencore-config-editor'
    | '/plist-editor'
    | '/plist-to-json'
    | '/plist-to-xml'
    | '/plist-viewer'
    | '/privacy'
    | '/sitemap.xml'
    | '/strings-editor'
    | '/stringsdict-editor'
    | '/what-is-a-plist-file'
    | '/xcconfig-editor'
    | '/xml-to-plist'
    | '/xml-vs-binary-plist'
    | '/$locale/about'
    | '/$locale/binary-plist-editor'
    | '/$locale/binary-plist-to-xml'
    | '/$locale/binary-plist-viewer'
    | '/$locale/entitlements-editor'
    | '/$locale/how-to-open-plist-on-windows'
    | '/$locale/json-to-plist'
    | '/$locale/mobileconfig-editor'
    | '/$locale/mobileprovision-viewer'
    | '/$locale/opencore-config-editor'
    | '/$locale/plist-editor'
    | '/$locale/plist-to-json'
    | '/$locale/plist-to-xml'
    | '/$locale/plist-viewer'
    | '/$locale/privacy'
    | '/$locale/strings-editor'
    | '/$locale/stringsdict-editor'
    | '/$locale/what-is-a-plist-file'
    | '/$locale/xcconfig-editor'
    | '/$locale/xml-to-plist'
    | '/$locale/xml-vs-binary-plist'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/binary-plist-editor'
    | '/binary-plist-to-xml'
    | '/binary-plist-viewer'
    | '/entitlements-editor'
    | '/how-to-open-plist-on-windows'
    | '/json-to-plist'
    | '/mobileconfig-editor'
    | '/mobileprovision-viewer'
    | '/opencore-config-editor'
    | '/plist-editor'
    | '/plist-to-json'
    | '/plist-to-xml'
    | '/plist-viewer'
    | '/privacy'
    | '/sitemap.xml'
    | '/strings-editor'
    | '/stringsdict-editor'
    | '/what-is-a-plist-file'
    | '/xcconfig-editor'
    | '/xml-to-plist'
    | '/xml-vs-binary-plist'
    | '/$locale/about'
    | '/$locale/binary-plist-editor'
    | '/$locale/binary-plist-to-xml'
    | '/$locale/binary-plist-viewer'
    | '/$locale/entitlements-editor'
    | '/$locale/how-to-open-plist-on-windows'
    | '/$locale/json-to-plist'
    | '/$locale/mobileconfig-editor'
    | '/$locale/mobileprovision-viewer'
    | '/$locale/opencore-config-editor'
    | '/$locale/plist-editor'
    | '/$locale/plist-to-json'
    | '/$locale/plist-to-xml'
    | '/$locale/plist-viewer'
    | '/$locale/privacy'
    | '/$locale/strings-editor'
    | '/$locale/stringsdict-editor'
    | '/$locale/what-is-a-plist-file'
    | '/$locale/xcconfig-editor'
    | '/$locale/xml-to-plist'
    | '/$locale/xml-vs-binary-plist'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/binary-plist-editor'
    | '/binary-plist-to-xml'
    | '/binary-plist-viewer'
    | '/entitlements-editor'
    | '/how-to-open-plist-on-windows'
    | '/json-to-plist'
    | '/mobileconfig-editor'
    | '/mobileprovision-viewer'
    | '/opencore-config-editor'
    | '/plist-editor'
    | '/plist-to-json'
    | '/plist-to-xml'
    | '/plist-viewer'
    | '/privacy'
    | '/sitemap.xml'
    | '/strings-editor'
    | '/stringsdict-editor'
    | '/what-is-a-plist-file'
    | '/xcconfig-editor'
    | '/xml-to-plist'
    | '/xml-vs-binary-plist'
    | '/$locale/about'
    | '/$locale/binary-plist-editor'
    | '/$locale/binary-plist-to-xml'
    | '/$locale/binary-plist-viewer'
    | '/$locale/entitlements-editor'
    | '/$locale/how-to-open-plist-on-windows'
    | '/$locale/json-to-plist'
    | '/$locale/mobileconfig-editor'
    | '/$locale/mobileprovision-viewer'
    | '/$locale/opencore-config-editor'
    | '/$locale/plist-editor'
    | '/$locale/plist-to-json'
    | '/$locale/plist-to-xml'
    | '/$locale/plist-viewer'
    | '/$locale/privacy'
    | '/$locale/strings-editor'
    | '/$locale/stringsdict-editor'
    | '/$locale/what-is-a-plist-file'
    | '/$locale/xcconfig-editor'
    | '/$locale/xml-to-plist'
    | '/$locale/xml-vs-binary-plist'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  BinaryPlistEditorRoute: typeof BinaryPlistEditorRoute
  BinaryPlistToXmlRoute: typeof BinaryPlistToXmlRoute
  BinaryPlistViewerRoute: typeof BinaryPlistViewerRoute
  EntitlementsEditorRoute: typeof EntitlementsEditorRoute
  HowToOpenPlistOnWindowsRoute: typeof HowToOpenPlistOnWindowsRoute
  JsonToPlistRoute: typeof JsonToPlistRoute
  MobileconfigEditorRoute: typeof MobileconfigEditorRoute
  MobileprovisionViewerRoute: typeof MobileprovisionViewerRoute
  OpencoreConfigEditorRoute: typeof OpencoreConfigEditorRoute
  PlistEditorRoute: typeof PlistEditorRoute
  PlistToJsonRoute: typeof PlistToJsonRoute
  PlistToXmlRoute: typeof PlistToXmlRoute
  PlistViewerRoute: typeof PlistViewerRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StringsEditorRoute: typeof StringsEditorRoute
  StringsdictEditorRoute: typeof StringsdictEditorRoute
  WhatIsAPlistFileRoute: typeof WhatIsAPlistFileRoute
  XcconfigEditorRoute: typeof XcconfigEditorRoute
  XmlToPlistRoute: typeof XmlToPlistRoute
  XmlVsBinaryPlistRoute: typeof XmlVsBinaryPlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binary-plist-editor': {
      id: '/binary-plist-editor'
      path: '/binary-plist-editor'
      fullPath: '/binary-plist-editor'
      preLoaderRoute: typeof BinaryPlistEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binary-plist-to-xml': {
      id: '/binary-plist-to-xml'
      path: '/binary-plist-to-xml'
      fullPath: '/binary-plist-to-xml'
      preLoaderRoute: typeof BinaryPlistToXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binary-plist-viewer': {
      id: '/binary-plist-viewer'
      path: '/binary-plist-viewer'
      fullPath: '/binary-plist-viewer'
      preLoaderRoute: typeof BinaryPlistViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entitlements-editor': {
      id: '/entitlements-editor'
      path: '/entitlements-editor'
      fullPath: '/entitlements-editor'
      preLoaderRoute: typeof EntitlementsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-open-plist-on-windows': {
      id: '/how-to-open-plist-on-windows'
      path: '/how-to-open-plist-on-windows'
      fullPath: '/how-to-open-plist-on-windows'
      preLoaderRoute: typeof HowToOpenPlistOnWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-plist': {
      id: '/json-to-plist'
      path: '/json-to-plist'
      fullPath: '/json-to-plist'
      preLoaderRoute: typeof JsonToPlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobileconfig-editor': {
      id: '/mobileconfig-editor'
      path: '/mobileconfig-editor'
      fullPath: '/mobileconfig-editor'
      preLoaderRoute: typeof MobileconfigEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobileprovision-viewer': {
      id: '/mobileprovision-viewer'
      path: '/mobileprovision-viewer'
      fullPath: '/mobileprovision-viewer'
      preLoaderRoute: typeof MobileprovisionViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencore-config-editor': {
      id: '/opencore-config-editor'
      path: '/opencore-config-editor'
      fullPath: '/opencore-config-editor'
      preLoaderRoute: typeof OpencoreConfigEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plist-editor': {
      id: '/plist-editor'
      path: '/plist-editor'
      fullPath: '/plist-editor'
      preLoaderRoute: typeof PlistEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plist-to-json': {
      id: '/plist-to-json'
      path: '/plist-to-json'
      fullPath: '/plist-to-json'
      preLoaderRoute: typeof PlistToJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plist-to-xml': {
      id: '/plist-to-xml'
      path: '/plist-to-xml'
      fullPath: '/plist-to-xml'
      preLoaderRoute: typeof PlistToXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plist-viewer': {
      id: '/plist-viewer'
      path: '/plist-viewer'
      fullPath: '/plist-viewer'
      preLoaderRoute: typeof PlistViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strings-editor': {
      id: '/strings-editor'
      path: '/strings-editor'
      fullPath: '/strings-editor'
      preLoaderRoute: typeof StringsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stringsdict-editor': {
      id: '/stringsdict-editor'
      path: '/stringsdict-editor'
      fullPath: '/stringsdict-editor'
      preLoaderRoute: typeof StringsdictEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-a-plist-file': {
      id: '/what-is-a-plist-file'
      path: '/what-is-a-plist-file'
      fullPath: '/what-is-a-plist-file'
      preLoaderRoute: typeof WhatIsAPlistFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xcconfig-editor': {
      id: '/xcconfig-editor'
      path: '/xcconfig-editor'
      fullPath: '/xcconfig-editor'
      preLoaderRoute: typeof XcconfigEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-to-plist': {
      id: '/xml-to-plist'
      path: '/xml-to-plist'
      fullPath: '/xml-to-plist'
      preLoaderRoute: typeof XmlToPlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-vs-binary-plist': {
      id: '/xml-vs-binary-plist'
      path: '/xml-vs-binary-plist'
      fullPath: '/xml-vs-binary-plist'
      preLoaderRoute: typeof XmlVsBinaryPlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/binary-plist-editor': {
      id: '/$locale/binary-plist-editor'
      path: '/binary-plist-editor'
      fullPath: '/$locale/binary-plist-editor'
      preLoaderRoute: typeof LocaleBinaryPlistEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/binary-plist-to-xml': {
      id: '/$locale/binary-plist-to-xml'
      path: '/binary-plist-to-xml'
      fullPath: '/$locale/binary-plist-to-xml'
      preLoaderRoute: typeof LocaleBinaryPlistToXmlRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/binary-plist-viewer': {
      id: '/$locale/binary-plist-viewer'
      path: '/binary-plist-viewer'
      fullPath: '/$locale/binary-plist-viewer'
      preLoaderRoute: typeof LocaleBinaryPlistViewerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/entitlements-editor': {
      id: '/$locale/entitlements-editor'
      path: '/entitlements-editor'
      fullPath: '/$locale/entitlements-editor'
      preLoaderRoute: typeof LocaleEntitlementsEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/how-to-open-plist-on-windows': {
      id: '/$locale/how-to-open-plist-on-windows'
      path: '/how-to-open-plist-on-windows'
      fullPath: '/$locale/how-to-open-plist-on-windows'
      preLoaderRoute: typeof LocaleHowToOpenPlistOnWindowsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/json-to-plist': {
      id: '/$locale/json-to-plist'
      path: '/json-to-plist'
      fullPath: '/$locale/json-to-plist'
      preLoaderRoute: typeof LocaleJsonToPlistRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/mobileconfig-editor': {
      id: '/$locale/mobileconfig-editor'
      path: '/mobileconfig-editor'
      fullPath: '/$locale/mobileconfig-editor'
      preLoaderRoute: typeof LocaleMobileconfigEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/mobileprovision-viewer': {
      id: '/$locale/mobileprovision-viewer'
      path: '/mobileprovision-viewer'
      fullPath: '/$locale/mobileprovision-viewer'
      preLoaderRoute: typeof LocaleMobileprovisionViewerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/opencore-config-editor': {
      id: '/$locale/opencore-config-editor'
      path: '/opencore-config-editor'
      fullPath: '/$locale/opencore-config-editor'
      preLoaderRoute: typeof LocaleOpencoreConfigEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plist-editor': {
      id: '/$locale/plist-editor'
      path: '/plist-editor'
      fullPath: '/$locale/plist-editor'
      preLoaderRoute: typeof LocalePlistEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plist-to-json': {
      id: '/$locale/plist-to-json'
      path: '/plist-to-json'
      fullPath: '/$locale/plist-to-json'
      preLoaderRoute: typeof LocalePlistToJsonRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plist-to-xml': {
      id: '/$locale/plist-to-xml'
      path: '/plist-to-xml'
      fullPath: '/$locale/plist-to-xml'
      preLoaderRoute: typeof LocalePlistToXmlRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plist-viewer': {
      id: '/$locale/plist-viewer'
      path: '/plist-viewer'
      fullPath: '/$locale/plist-viewer'
      preLoaderRoute: typeof LocalePlistViewerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/strings-editor': {
      id: '/$locale/strings-editor'
      path: '/strings-editor'
      fullPath: '/$locale/strings-editor'
      preLoaderRoute: typeof LocaleStringsEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/stringsdict-editor': {
      id: '/$locale/stringsdict-editor'
      path: '/stringsdict-editor'
      fullPath: '/$locale/stringsdict-editor'
      preLoaderRoute: typeof LocaleStringsdictEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/what-is-a-plist-file': {
      id: '/$locale/what-is-a-plist-file'
      path: '/what-is-a-plist-file'
      fullPath: '/$locale/what-is-a-plist-file'
      preLoaderRoute: typeof LocaleWhatIsAPlistFileRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/xcconfig-editor': {
      id: '/$locale/xcconfig-editor'
      path: '/xcconfig-editor'
      fullPath: '/$locale/xcconfig-editor'
      preLoaderRoute: typeof LocaleXcconfigEditorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/xml-to-plist': {
      id: '/$locale/xml-to-plist'
      path: '/xml-to-plist'
      fullPath: '/$locale/xml-to-plist'
      preLoaderRoute: typeof LocaleXmlToPlistRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/xml-vs-binary-plist': {
      id: '/$locale/xml-vs-binary-plist'
      path: '/xml-vs-binary-plist'
      fullPath: '/$locale/xml-vs-binary-plist'
      preLoaderRoute: typeof LocaleXmlVsBinaryPlistRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleBinaryPlistEditorRoute: typeof LocaleBinaryPlistEditorRoute
  LocaleBinaryPlistToXmlRoute: typeof LocaleBinaryPlistToXmlRoute
  LocaleBinaryPlistViewerRoute: typeof LocaleBinaryPlistViewerRoute
  LocaleEntitlementsEditorRoute: typeof LocaleEntitlementsEditorRoute
  LocaleHowToOpenPlistOnWindowsRoute: typeof LocaleHowToOpenPlistOnWindowsRoute
  LocaleJsonToPlistRoute: typeof LocaleJsonToPlistRoute
  LocaleMobileconfigEditorRoute: typeof LocaleMobileconfigEditorRoute
  LocaleMobileprovisionViewerRoute: typeof LocaleMobileprovisionViewerRoute
  LocaleOpencoreConfigEditorRoute: typeof LocaleOpencoreConfigEditorRoute
  LocalePlistEditorRoute: typeof LocalePlistEditorRoute
  LocalePlistToJsonRoute: typeof LocalePlistToJsonRoute
  LocalePlistToXmlRoute: typeof LocalePlistToXmlRoute
  LocalePlistViewerRoute: typeof LocalePlistViewerRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleStringsEditorRoute: typeof LocaleStringsEditorRoute
  LocaleStringsdictEditorRoute: typeof LocaleStringsdictEditorRoute
  LocaleWhatIsAPlistFileRoute: typeof LocaleWhatIsAPlistFileRoute
  LocaleXcconfigEditorRoute: typeof LocaleXcconfigEditorRoute
  LocaleXmlToPlistRoute: typeof LocaleXmlToPlistRoute
  LocaleXmlVsBinaryPlistRoute: typeof LocaleXmlVsBinaryPlistRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleBinaryPlistEditorRoute: LocaleBinaryPlistEditorRoute,
  LocaleBinaryPlistToXmlRoute: LocaleBinaryPlistToXmlRoute,
  LocaleBinaryPlistViewerRoute: LocaleBinaryPlistViewerRoute,
  LocaleEntitlementsEditorRoute: LocaleEntitlementsEditorRoute,
  LocaleHowToOpenPlistOnWindowsRoute: LocaleHowToOpenPlistOnWindowsRoute,
  LocaleJsonToPlistRoute: LocaleJsonToPlistRoute,
  LocaleMobileconfigEditorRoute: LocaleMobileconfigEditorRoute,
  LocaleMobileprovisionViewerRoute: LocaleMobileprovisionViewerRoute,
  LocaleOpencoreConfigEditorRoute: LocaleOpencoreConfigEditorRoute,
  LocalePlistEditorRoute: LocalePlistEditorRoute,
  LocalePlistToJsonRoute: LocalePlistToJsonRoute,
  LocalePlistToXmlRoute: LocalePlistToXmlRoute,
  LocalePlistViewerRoute: LocalePlistViewerRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleStringsEditorRoute: LocaleStringsEditorRoute,
  LocaleStringsdictEditorRoute: LocaleStringsdictEditorRoute,
  LocaleWhatIsAPlistFileRoute: LocaleWhatIsAPlistFileRoute,
  LocaleXcconfigEditorRoute: LocaleXcconfigEditorRoute,
  LocaleXmlToPlistRoute: LocaleXmlToPlistRoute,
  LocaleXmlVsBinaryPlistRoute: LocaleXmlVsBinaryPlistRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  BinaryPlistEditorRoute: BinaryPlistEditorRoute,
  BinaryPlistToXmlRoute: BinaryPlistToXmlRoute,
  BinaryPlistViewerRoute: BinaryPlistViewerRoute,
  EntitlementsEditorRoute: EntitlementsEditorRoute,
  HowToOpenPlistOnWindowsRoute: HowToOpenPlistOnWindowsRoute,
  JsonToPlistRoute: JsonToPlistRoute,
  MobileconfigEditorRoute: MobileconfigEditorRoute,
  MobileprovisionViewerRoute: MobileprovisionViewerRoute,
  OpencoreConfigEditorRoute: OpencoreConfigEditorRoute,
  PlistEditorRoute: PlistEditorRoute,
  PlistToJsonRoute: PlistToJsonRoute,
  PlistToXmlRoute: PlistToXmlRoute,
  PlistViewerRoute: PlistViewerRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StringsEditorRoute: StringsEditorRoute,
  StringsdictEditorRoute: StringsdictEditorRoute,
  WhatIsAPlistFileRoute: WhatIsAPlistFileRoute,
  XcconfigEditorRoute: XcconfigEditorRoute,
  XmlToPlistRoute: XmlToPlistRoute,
  XmlVsBinaryPlistRoute: XmlVsBinaryPlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
